### ISSUE TITLE
[README.md] The example link is dead

### ISSUE THREAD

**Issue by francoismassart** [webpack-contrib/component-webpack-plugin#7]
Inside the `README.md`...

`see an example here: webpack/webpack/examples/component`

The link points to https://github.com/webpack/webpack/tree/master/examples/component

Which show an error page...

Indeed there is no (more) `component` folder...
https://github.com/webpack/webpack/tree/master/examples

Latest commit with the folder I found was:
https://github.com/webpack/webpack/tree/8d49b5ba99470e3147e541c14b3019bea14b6666/examples/component

**Comment by queckezz** [comment]
Thats because `Component` itself isn't maintained anymore. So i think it makes sense that the there are no more component examples. See https://github.com/componentjs/component/issues/639

**Comment by bebraw** [comment]
I dropped the link. Thanks for the heads up.
